[package]
name = "gt7_portforward"
authors = ["skycloudd"]
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.42", features = ["derive"] }
env_logger = "0.11.8"
gran-turismo-query = "0.3.0"
log = "0.4.27"
